# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "main.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nmain.proto"!\n\x0fGetImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t"\x96\x01\n\x10GetImageResponse\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.GetImageResponse.Status\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t"3\n\x06Status\x12\x0e\n\nPROCESSING\x10\x00\x12\r\n\tCOMPLETED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x32\x46\n\x0fGetImageService\x12\x33\n\x08GetImage\x12\x10.GetImageRequest\x1a\x11.GetImageResponse"\x00\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "main_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETIMAGEREQUEST"]._serialized_start = 14
    _globals["_GETIMAGEREQUEST"]._serialized_end = 47
    _globals["_GETIMAGERESPONSE"]._serialized_start = 50
    _globals["_GETIMAGERESPONSE"]._serialized_end = 200
    _globals["_GETIMAGERESPONSE_STATUS"]._serialized_start = 149
    _globals["_GETIMAGERESPONSE_STATUS"]._serialized_end = 200
    _globals["_GETIMAGESERVICE"]._serialized_start = 202
    _globals["_GETIMAGESERVICE"]._serialized_end = 272
# @@protoc_insertion_point(module_scope)
